module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "collection-1-gray-00": "var(--collection-1-gray-00)",
        "collection-1-gray-100": "var(--collection-1-gray-100)",
        "collection-1-gray-200": "var(--collection-1-gray-200)",
        "collection-1-gray-300": "var(--collection-1-gray-300)",
        "collection-1-gray-400": "var(--collection-1-gray-400)",
        "collection-1-gray-50": "var(--collection-1-gray-50)",
        "collection-1-gray-500": "var(--collection-1-gray-500)",
        "collection-1-gray-600": "var(--collection-1-gray-600)",
        "collection-1-gray-700": "var(--collection-1-gray-700)",
        "collection-1-gray-800": "var(--collection-1-gray-800)",
        "collection-1-gray-900": "var(--collection-1-gray-900)",
        "collection-1-green-100": "var(--collection-1-green-100)",
        "collection-1-green-200": "var(--collection-1-green-200)",
        "collection-1-green-300": "var(--collection-1-green-300)",
        "collection-1-green-400": "var(--collection-1-green-400)",
        "collection-1-green-50": "var(--collection-1-green-50)",
        "collection-1-green-500": "var(--collection-1-green-500)",
        "collection-1-green-600": "var(--collection-1-green-600)",
        "collection-1-green-700": "var(--collection-1-green-700)",
        "collection-1-green-800": "var(--collection-1-green-800)",
        "collection-1-green-900": "var(--collection-1-green-900)",
        "collection-1-purple-100": "var(--collection-1-purple-100)",
        "collection-1-purple-200": "var(--collection-1-purple-200)",
        "collection-1-purple-300": "var(--collection-1-purple-300)",
        "collection-1-purple-400": "var(--collection-1-purple-400)",
        "collection-1-purple-50": "var(--collection-1-purple-50)",
        "collection-1-purple-500": "var(--collection-1-purple-500)",
        "collection-1-purple-600": "var(--collection-1-purple-600)",
        "collection-1-purple-700": "var(--collection-1-purple-700)",
        "collection-1-purple-800": "var(--collection-1-purple-800)",
        "collection-1-purple-900": "var(--collection-1-purple-900)",
        "collection-1-red-300": "var(--collection-1-red-300)",
        "collection-1-red-400": "var(--collection-1-red-400)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        blockquote: "var(--blockquote-font-family)",
        body: "var(--body-font-family)",
        "body-medium": "var(--body-medium-font-family)",
        detail: "var(--detail-font-family)",
        "h-1": "var(--h-1-font-family)",
        "h-2": "var(--h-2-font-family)",
        "h-3": "var(--h-3-font-family)",
        "h-4": "var(--h-4-font-family)",
        "inline-code": "var(--inline-code-font-family)",
        large: "var(--large-font-family)",
        lead: "var(--lead-font-family)",
        list: "var(--list-font-family)",
        p: "var(--p-font-family)",
        "p-ui": "var(--p-ui-font-family)",
        "p-ui-medium": "var(--p-ui-medium-font-family)",
        small: "var(--small-font-family)",
        "suble-semibold": "var(--suble-semibold-font-family)",
        subtle: "var(--subtle-font-family)",
        "subtle-medium": "var(--subtle-medium-font-family)",
        "table-head": "var(--table-head-font-family)",
        "table-item": "var(--table-item-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        bright: "var(--bright)",
        gray: "var(--gray)",
        "gray-small": "var(--gray-small)",
        green: "var(--green)",
        "light-gray": "var(--light-gray)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
